name: geomag
description: Translate GPS location data to geo-magnetic data such as magnetic declination.
version: 0.2.1
homepage: https://github.com/jifalops/geomag

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.19.0

dev_dependencies:
  test: ^1.6.5